### PR TITLE
Fix issue of button not disabled while adding todo without title

### LINKED ISSUE #216: Empty ToDo section in RHS closes on saving without any error
If a user open the add todo section in RHS and clicks on save button, it closes without any error.
**Steps to reproduce:-**
1. Click on add todo button in RHS of todo plugin.
2. Click on the save button keeping all the fields empty.

The user should receive an error instead of closing the section.

### PR DESCRIPTION
**Pull request by ayusht2810**
#### Summary
- Fix issue of button not disabled while adding todo without title
- Added disabled prop in the button

#### Screenshot
image

#### Ticket Link
Fixes #216 

#### Checklist
- [x] Completed dev testing
- [x] `make test` Ran test cases and ensured they are passing
- [x] `make check-style` Ran style check and ensured both webapp and server pass the checks

### CODE REVIEW

File: webapp/src/components/add_issue/add_issue.jsx [hunk 1]
```diff
@@ -143,7 +143,7 @@ export default class AddIssue extends React.PureComponent {
                                 <React.Fragment>
                                     <TextareaAutosize
                                         style={style.textareaResizeMessage}
-                                        placeholder='Enter a title'
+                                        placeholder='Enter a title *'
```
Comment (mickmister) [inline webapp/src/components/add_issue/add_issue.jsx:146]: We usally want the asterisk to be red or probably `error-text` class in this case. Also this should be a `hint` and not `placeholder` right?

Comment (ayusht2810) [reply webapp/src/components/add_issue/add_issue.jsx:146]: @mickmister The `TextareaAutosize` component doesn't have any `hint` prop in it. Also, the placeholder only supports `string` type, that's why we were not able to update the color.
Should we add a `label` element and add stylings to support this?

**Review by raghavaggarwal2308 — APPROVED** [review]

File: webapp/src/components/add_issue/add_issue.jsx (hunk 1 above)
Comment (mickmister) [reply webapp/src/components/add_issue/add_issue.jsx:146]: That's an external library we're using here. If it's not trivial to change the color of the asterisk, then maybe we just don't use an asterisk here. @asaadmahmood What do you think?

Comment (raghavaggarwal2308) [reply webapp/src/components/add_issue/add_issue.jsx:146]: @asaadmahmood Gentle reminder for this

Comment (raghavaggarwal2308) [reply webapp/src/components/add_issue/add_issue.jsx:146]: @asaadmahmood Gentle reminder for this

Comment (asaadmahmood) [reply webapp/src/components/add_issue/add_issue.jsx:146]: @ayusht2810 We can get rid of the asterik, the button is disabled, its fine that the title needs to be entered.

**Review by asaadmahmood — APPROVED** [review]
LGTM
