### PR TITLE
GH-177 - Minor UI tweaks and regression fix

### LINKED ISSUE #177: Adding a ToDo from a post does not move the [Permalink]
Previously when creating a To Do from a Mattermost post the `[Permalink]` is moved to a new line below the quoted text. 
Now there is no white space and the link is immediately after the text. 
image

This screen shows the previous and current behavior side by side.
image
image

The issue is especially bothersome because trying to use the `enter` or `return` key to add the line break yourself will save the data. 0/5 of this is desirable once the bug is fixed.

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
GH-177 - Minor UI tweaks and regression fix
- Adds permalink to the new line instead of the same line.
- Allowed shift + enter shortcut to add new line.

#### Ticket Link
Fixes #177

### CODE REVIEW

**Review by larkox — APPROVED** [review]

File: webapp/src/components/sidebar_right/sidebar_right.jsx [hunk 1]
```diff
@@ -217,7 +217,9 @@ export default class SidebarRight extends React.PureComponent {
                 >
                     <div className='todolist-header'>
                         <MenuWrapper>
-                            <button style={style.todoHeader}>
+                            <button
+                                className='todolist-header__dropdown'
```
Comment (mickmister) [inline webapp/src/components/sidebar_right/sidebar_right.jsx:221]: Since `style.todoHeader` isn't referenced anywhere, can we remove it from the `style` object?

**Review by mickmister — APPROVED** [review]

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Line break re-added
- Users can use `shift`+`return` to add line breaks manually

LGTM!
